package com.bitworks.rtb.writer

import com.bitworks.rtb.model.ad.response.AdResponse

/**
  * Writer for [[com.bitworks.rtb.model.ad.response.AdResponse AdResponse]].
  *
  * @author Egor Ilchenko
  */
trait AdResponseWriter {

  /**
    * Returns generated byte array.
    *
    * @param response [[com.bitworks.rtb.model.ad.response.AdResponse AdResponse]] object
    */
  def write(response: AdResponse): Array[Byte]
}
