package com.bitworks.rtb.writer

import com.bitworks.rtb.model.request.BidRequest

/**
  * Writer for [[com.bitworks.rtb.model.request.BidRequest BidRequest]].
  *
  * @author Pavel Tomskikh
  */
trait BidRequestWriter {

  /**
    * Returns generated byte array.
    *
    * @param bidRequest a [[com.bitworks.rtb.model.request.BidRequest BidRequest]] object
    */
  def write(bidRequest: BidRequest): Array[Byte]

}
