@startuml

title RTB request processing

participant Publisher
participant App
participant Factory
participant Parser
participant Validator
participant Writer
participant BidActory
participant Bidders

note left of Publisher
    Request, Response are
    serialized objects.
    RequestModel, ResponseModel
    are just objects
end note

Publisher -> App: AdRequest
activate App

App -> Parser: AdRequest
activate Parser
App <-- Parser: AdRequestModel
deactivate Parser

App -> Validator: AdRequestModel
activate Validator
App <-- Validator: AdRequestModel is valid
deactivate Validator

App -> Factory: AdRequestModel
activate Factory
App <-- Factory: BidRequestModel
deactivate Factory

App -> BidActory: BidRequestModel
activate BidActory

BidActory -> Writer: BidRequestModel
activate Writer
Writer --> BidActory: BidRequest
deactivate Writer

BidActory -> Bidders: BidRequest
activate Bidders
BidActory <-- Bidders: BidResponse
deactivate Bidders

BidActory -> Parser: BidResponse
activate Parser
BidActory <-- Parser: BidResponseModel
deactivate Parser

BidActory -> Validator: BidResponseModel
activate Validator
BidActory <-- Validator: BidResponseModel is valid
deactivate Validator

App <-- BidActory: BidResponseModel
deactivate BidActory

App -> App: Auction

App -> Bidders: Win Notice
alt If Ad url/markup not in the BidResponse
    App <- Bidders: Ad url/markup
end

App -> Factory: BidResponseModel
activate Factory
App <-- Factory: AdResponseModel
deactivate Factory

App -> Writer: AdResponseModel
activate Writer
App <-- Writer: AdResponse
deactivate Writer

App --> Publisher: AdResponse
deactivate App

@enduml
