@startuml

title RTB request processing (part 2/3)

participant Publisher
participant Exchange
participant Factory
participant Parser
participant Validator
participant Writer
participant BidActor
participant WinBidActor
participant Bidder

activate Exchange
Exchange ->> BidActor: BidRequest
activate BidActor

BidActor -> Writer: BidRequest
activate Writer
Writer --> BidActor: HTTP request
deactivate Writer

BidActor -> Bidder: HTTP request
activate Bidder
opt Got HTTP response
    BidActor <-- Bidder: HTTP response
    deactivate Bidder

    BidActor -> Parser: HTTP response
    activate Parser

    BidActor <-- Parser: BidResponse/Parsing fail
    deactivate Parser
    opt HTTP response parsed to BidResponse
        BidActor -> Validator: BidResponse
        activate Validator
        BidActor <-- Validator: true/false
        deactivate Validator
        opt BidResponse is valid
            Exchange <<- BidActor: BidResponse
        end
    end
end

deactivate BidActor

Exchange -> Exchange: Auction

@enduml
